repository:
  name: test-repo
  description: Test repo
  # homepage: https://example.com/
  private: false
  has_issues: true
  has_wiki: false
  # has_downloads: true
  default_branch: master
labels:
  - name: bug
    color: d73a4a
    description: Something isn't working
  - name: duplicate
    color: cfd3d7
    description: This issue or pull request already exists
  - name: enhancement
    color: a2eeef
    description: New feature or request
  - name: good first issue
    color: 7057ff
    description: Good for newcomers
  - name: help wanted
    color: 008672
    description: Extra attention is needed
  - name: invalid
    color: e4e669
    description: This doesn't seem right
  - name: needs more info
    color: dfc6ff
    description: More information is required
  - name: polls
    color: ededed
    description: This issue or pull request has polls
  - name: question
    color: d876e3
    description: Further information is requested
  - name: stale
    color: ffffff
    description: Inactive issue or pull request
  - name: top
    color: f442c2
    description: Top issue or pull request
  - name: no fix
    color: ffffff
    description: This will not be worked on
